- name: mysql module
  hosts: mysql
  become: yes
  tasks:
  - name: disable mysql default version
    ansible.builtin.command: dnf module disable mysql -y
  
  - name: copy mysql repo 
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
  
  - name: install mysql community server
    ansible.builtin.dnf:
      name: mysql-community-server
      state: present
      disable_gpg_check: true

  - name: Start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: set upuser and password got mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1




# - name: mysql module
#   hosts: mysql
#   become: yes

#   tasks:

#   - name: disable mysql default version
#     ansible.builtin.command:
#       cmd: dnf module disable mysql -y


#   - name: copy mysql repo
#     ansible.builtin.copy:
#       src: mysql.repo
#       dest: /etc/yum.repos.d/mysql.repo


#   - name: install yum utils
#     ansible.builtin.dnf:
#       name: yum-utils
#       state: present


#   # Check mysql installed or not

#   - name: check mysql already installed
#     ansible.builtin.command:
#       cmd: rpm -q mysql-community-server
#     register: mysql_check
#     ignore_errors: true


#   # Download only first time

#   - name: remove old rpm files
#     ansible.builtin.shell:
#       cmd: rm -f *.rpm
#     when: mysql_check.rc != 0


#   - name: download mysql packages
#     ansible.builtin.command:
#       cmd: dnf download mysql-community-server.x86_64 --resolve --arch=x86_64
#     when: mysql_check.rc != 0


#   # Install mysql 5.7 old rpm in RHEL9

#   - name: install mysql community server ignoring digest
#     ansible.builtin.shell:
#       cmd: rpm -ivh --nodigest --nofiledigest *.rpm
#     when: mysql_check.rc != 0


#   - name: start and enable mysql
#     ansible.builtin.service:
#       name: mysqld
#       state: started
#       enabled: yes


#   # Check current password

#   - name: check mysql password already configured
#     ansible.builtin.command:
#       cmd: mysql -uroot -pRoboShop@1 -e "show databases;"
#     register: mysql_login
#     ignore_errors: true


#   # Get temporary password generated by mysql

#   - name: get mysql temporary password
#     ansible.builtin.shell:
#       cmd: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}' | tail -1
#     register: mysql_temp_password
#     when: mysql_login.rc != 0


#   # Change temp password to RoboShop@1

#   - name: set mysql root password
#     ansible.builtin.shell:
#       cmd: mysql --connect-expired-password -uroot -p'{{ mysql_temp_password.stdout }}' -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"
#     when: mysql_login.rc != 0


#   # Create remote access user

#   - name: create remote root user
#     ansible.builtin.command:
#       cmd: mysql -uroot -pRoboShop@1 -e "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'RoboShop@1';"


#   - name: grant mysql remote permissions
#     ansible.builtin.command:
#       cmd: mysql -uroot -pRoboShop@1 -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"


#   - name: flush privileges
#     ansible.builtin.command:
#       cmd: mysql -uroot -pRoboShop@1 -e "FLUSH PRIVILEGES;"